import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>q&a Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>a</div>
      <div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ
      <div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ
      <div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ
      <div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ
      <div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ
      <div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ<div>a</div>ﬂ
      <div>a</div>ﬂ
    </div>
  );
}
